version: '3'
services:
  website:
    build: .
    image: gusta-website:latest
    container_name: gusta-website
  proxy:
    image: nginx
    container_name: gusta-website-proxy
    restart: always
    depends_on:
      - website
      - proxy-reloader
      - letsencrypt
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
  proxy-reloader:
    image: jwilder/docker-gen
    command: -notify-sighup gusta-website-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: gusta-website-proxy-reloader
    restart: always
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: gusta-website-letsencrypt
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=gusta-website-proxy
      - NGINX_DOCKER_GEN_CONTAINER=gusta-website-proxy-reloader
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
volumes:
  conf:
  vhost:
  html:
  certs:
