version: '3'
services:
  builder:
    build: .
    image: gusta-website:latest
    container_name: gusta-website-builder
  website:
    image: jwilder/nginx-proxy
    container_name: gusta-website-proxy
    depends_on:
      - builder
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PWD}/certs:/etc/nginx/certs
      - ${PWD}/certs/dhparam.pem:/etc/nginx/dhparam/dhparam.pem
      - /var/run/docker.sock:/tmp/docker.sock:ro
